config/routes.rb
Rails.application.routes.draw do
  
  get 'users/new'
  get 'sessions/new'
  get 'trips/index1'
  get 'welcome/index'

=begin
  resources :articles do
    resources :comments
  end
=end
  
  get    '/signup',  to: 'users#new'
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  delete '/logout',  to: 'sessions#destroy'
  
  resources :users
  resources :welcome
  resources :myjourney
#  resources :trips

  resources :trips do
    resources :ovrspds
  end
    
  namespace :api do
    namespace :v1 do
=begin
      resources :users, only: [:index, :create, :show, :update, :destroy]
      resources :microposts, only: [:index, :create, :show, :update, :destroy]
=end
    end
  end
  
  root :controller=> "sessions", :action=> "new"
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/myjourney.rb
class Myjourney < ApplicationRecord
end

app/models/ovrspd.rb
class Ovrspd < ApplicationRecord
  
  belongs_to :trip
  
end

app/models/trip.rb
class Trip < ApplicationRecord
  
  validates :journey_name, :imei_no, presence: true
  
  has_many :ovrspds

  def as_json(options={})
    { :journey_name => self.journey_name, :imei_no => self.imei_no, :start_latitude => self.start_latitude,
      :start_longitude => self.start_longitude, :stop_latitude => self.stop_latitude, :stop_longitude => self.stop_longitude,
      :avg_spd => self.avg_spd, :remarks => self.remarks }
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  
#  require 'digest/sha1'
  
  attr_accessor :password
  EMAIL_REGEX = /^[A-Z0-9._%+-]+@[A-Z0-9.-]+\.[A-Z]{2,4}$/i
 # validates :username, :presence => true, :uniqueness => true, :length => { :in => 3..20 }
#  validates :email, :presence => true, :uniqueness => true, :format => EMAIL_REGEX
  validates :password,:presence => true
#  validates_length_of :password, :in => 6..20, :on => :create

#  has_secure_password

  def authenticate?(email, password)
    user = User.find_by_email email
    return nil  if user.nil?
    return user if user.has_password?(password)
  end
  
#  attr_accessible :email, :password
  
=begin
  before_save :encrypt_password
  after_save :clear_password
  
  def encrypt_password
    if password.present?
      self.salt = random_string(8) if self.salt == nil
      self.hashed_password = Digest::SHA1.hexdigest(self.salt + self.password) unless self.password.nil?
    end
  end
  
  def clear_password
    self.password = nil
  end
=end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/myjourney_controller.rb
class MyjourneyController < ApplicationController
  
  def index
    @journey= Myjourney.all
    @journey_pagi = @journey.paginate(:page => params[:page], :per_page => 4)
  end
  
  def show
    @journey= Myjourney.find(params[:id])
  end
  
  def new
=begin
    @journey= Myjourney.new
=end
  end
  
  def edit
    @journey= Myjourney.find(params[:id])
  end

  def create    
    @journey= Myjourney.new(journey_params)
    
    if @journey.save
      redirect_to @journey
    else
      render 'new'
    end
  end
  
  def update
    @journey= Myjourney.find(params[:id])
    
    if @journey.update(journey_params)
      redirect_to @journey
    else
      render 'edit'  
    end
  end
  
  def destroy
    @journey = Myjourney.find(params[:id])
    @journey.destroy
   
    redirect_to myjourney_path
  end
  
  
  private
  def journey_params
    params.require(:myjourney).permit(:journey_name,:imei_no,:start_latitude,:start_longitude,:remarks)
  end
  
end

app/controllers/ovrspds_controller.rb
class OvrspdsController < ApplicationController
  
  def create
    @trip = Trip.find(params[:trip_id])
    @ovrspd = @trip.ovrspds.create(ovrspd_params)
    redirect_to trip_path(@trip)
  end
  
  private
    def ovrspd_params
      params.required(:ovrspd).permit(:over_speed,:ovrspd_latitude,:ovrspd_longitude)
    end
      
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def new
    
  end

  def create
    user = User.find_by(email: params[:session][:email].downcase)
    
=begin
    if (user.nil? == false) 
        if user.authenticate(params[:password]) 
          puts user.authenticate(params[:password])
          puts "NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN NaN Batman!"
          session[:user_id] = user.id
          flash[:success] = "Thanks for logging in!"
          redirect_to :controller => 'trips'
        else 
          puts user.authenticate(params[:password])
          puts "waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka waka"
          flash[:error] = "There was an error logging in. Please check your email and password"
          render action: "new"
        end
      else
        flash[:error] = "There was an error logging in. Please check your email and password"
        render action: "new"
      end
=end
  
#    if user && user.authenticate(params[:password])
      
      if user
        redirect_to :controller => 'welcome', :id => user.id
#      log_in user

#      redirect_to :controller => 'trips', :id => user.id
  
    else
      
      flash[:danger] = 'Invalid email/password combination'
      render 'new'
    end
      
      
  end
    
    
    
  




  def destroy
  end
  
end

app/controllers/trips_controller.rb
class TripsController < ApplicationController
  
  def index
    @trip = Trip.all
    @trip_pagi = @trip.paginate(:page => params[:page], :per_page => 4)
    #render :json => @trip
    @user = User.find(params[:id])
  end

  def index1
    @trip = Trip.all
    render :json => @trip
    @user = User.find(params[:id])
  end
  
  def show
    @trip = Trip.find(params[:id])
  end
  
  def new
    @trip = Trip.new
  end
  
  def edit
    @trip = Trip.find(params[:id])
  end
  
  def create
    @trip = Trip.new(trip_params)
    
    if @trip.save
      redirect_to @trip
    else
      render 'new'
    end
      
  end
  
  def edit
    @trip = Trip.find(params[:id])
  end
  
  def update
    @trip = Trip.find(params[:id])
    
    if @trip.update(trip_params)
      redirect_to @trip
    else
      render 'edit'
    end
  end
  
  
  
    
  private
    def trip_params
      params.require(:trip).permit(:journey_name,:imei_no,:start_latitude,:start_longitude,:stop_latitude,:stop_longitude,:avg_spd,:remarks)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def new
    @user = User.new 
  end
  
  def create
    @user = User.new(params[:user])
    if @user.save
      flash[:notice] = "You signed up successfully"
      flash[:color]= "valid"
    else
      flash[:notice] = "Form is invalid"
      flash[:color]= "invalid"
    end
    render "new"
  end
  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  
  def index
    @user = User.find(params[:id])
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/myjourney_helper.rb
module MyjourneyHelper
end

app/helpers/ovrspds_helper.rb
module OvrspdsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  
  def log_in(user)
    session[:user_id] = user.id
  end
  
end

app/helpers/trips_helper.rb
module TripsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MyTrip</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/myjourney/edit.html.erb
<h1>Editing Journey</h1>

<%= form_for :myjourney, url: myjourney_path(@journey), method: :patch do |f| %>

  <% if @journey.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@journey.errors.count, "error") %> prohibited
        this article from being saved:
      </h2>
      <ul>
        <% @journey.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  
  <p>
    <%= f.label "Journey Name:" %><br>
    <%= f.text_field :title %>
  </p>
 
  <p>
    <%= f.label "Text:" %><br>
    <%= f.text_area :text %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
	
<% end %>

<%= link_to 'Back', myjourney_path %>

app/views/myjourney/index.html.erb
<!--<h1>Welcome To ROR App.</h1>-->

<div class = "titledisplay">List Articles</div>
<% h=@journey_pagi.count%>
<h3>Total: <%= h%></h3>
<h4><%= link_to 'Create New article', new_myjourney_path %></h4> 
<h5><%= link_to 'Back', controller: 'welcome' %></h5>

<div>
  <table border="8", width="80%">
	<tr>
		<th>Journey Name:</th>
		<th>IMEI No</th>
		<th colspan="5"></th>
	</tr>
	<%shw=0%>
	<% @journey_pagi.each_with_index do |journey,i| %>
		<tr>
			<% i= i+1 %>
			<td><%= journey.journey_name %></td>
			<td><%= journey.imei_no %></td>
			<td><%= link_to "Show", myjourney_path(journey) %></td>
			<td><%= link_to "Edit", edit_myjourney_path(journey) %></td>
			<td><%= link_to "Delete", myjourney_path(journey),
              		method: :delete,
              		data: { confirm: 'Are you sure?' } %></td>
				<% shw=i %>
		</tr>
				
	<% end %>
	
	<h3>Showing: <%= shw %></h3>		
		
  </table>
  <br />
  <%= will_paginate @journey_pagi %>
</div>

app/views/myjourney/new.html.erb
<div class='journeytitle'> Add New Journey</div>

<%= form_for :myjourney, url: myjourney_path do |f| %>

<!--
	<% if @journey.errors.any? %>
	    <div id="error_explanation">
	      <h2>
	        <%= pluralize(@journey.errors.count, "error") %> prohibited
	        this article from being saved:
	      </h2>
	      <ul>
	        <% @journey.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
	<% end %>
-->

	<p>
		<%= f.label "Journey Name:" %>
		<%= f.text_field :journey_name %>
	</p>
	
	<p>
		<%= f.label "IMEI NO:" %>
		<%= f.text_field :imei_no %>
	</p>
	
	<p>
		<%= f.label "Start Latitude:" %>
		<%= f.text_field :start_latitude %>
	</p>
	
	<p>
		<%= f.label "Start Longitude:" %>
		<%= f.text_field :start_longitude %>
	</p>
	
	<p>
		<%= f.label "Remarks:" %>
		<%= f.text_field :remarks %>
	</p>
	
	<br/>
	
	<p>
		<%= f.submit %>
	</p>

<% end %>

app/views/myjourney/show.html.erb
<div class = "titledisplay">
	<!--<%= image_tag "ROR Image.png", size: "60x60" %>-->
	Show Journey
</div>

<div>
  <div class = "labledisplay">Journey Name:</div>
  <div class = "namedisplay"><%= @journey.journey_name %></div>
</div>
 
<div>
  <div class = "labledisplay">IMEI NO:</div>
  <div class = "namedisplay"><%= @journey.imei_no %></div>
</div>


<%= link_to 'Edit', edit_myjourney_path(@journey) %> |
<%= link_to 'Back', myjourney_path %>

app/views/trips/edit.html.erb
<h1>Edit Journey</h1>

<%= form_for :trip, url: trip_path(@trip), method: :patch do |f| %>

  <p>
    <%= f.label "Journey Name:" %><br>
    <%= f.text_field :journey_name %>
  </p>
 
  <p>
    <%= f.label "IMEI No:" %><br>
    <%= f.text_area :imei_no %>
  </p>
  
  <p>
    <%= f.label "Start Latitude:" %><br>
    <%= f.text_area :start_latitude %>
  </p>
  
  <p>
    <%= f.label "Start Latitude:" %><br>
    <%= f.text_area :start_longitude %>
  </p>
  
  <p>
    <%= f.label "Stop Latitude:" %><br>
    <%= f.text_area :stop_latitude %>
  </p>
  
  <p>
    <%= f.label "Stop Longitude:" %><br>
    <%= f.text_area :stop_longitude %>
  </p>
  
  <p>
    <%= f.label "Average Speed" %><br>
    <%= f.text_area :avg_spd %>
  </p>
 
  <p>
    <%= f.submit %>
  </p>
	
<% end %>

app/views/trips/index.html.erb
<h1>Listing Trips</h1>

<%= link_to 'Add New Journey', new_trip_path %>

<br />

<table border="5", width="80%">
  <tr>
    <th>Journey Name</th>
    <th>IMEI No</th>
    <th>Start Latitude</th>
    <th>Start Longitude</th>
    <th>Stop Latitude</th>
    <th>Stop Longitude</th>
    <th>Average Speed</th>
    <th></th>
  </tr>
 
  <% @trip.each do |trp| %>
    <tr>
      <td><%= trp.journey_name %></td>
      <td><%= trp.imei_no %></td>
      <td><%= trp.start_latitude %></td>
      <td><%= trp.start_longitude %></td>
      <td><%= trp.stop_latitude %></td>
      <td><%= trp.stop_longitude %></td>
      <td><%= trp.avg_spd %></td>
      <td><%= link_to 'Show', trip_path(trp) %></td>
      <td><%= link_to 'Edit', edit_trip_path(trp) %></td>
    </tr>
  <% end %>
</table>

app/views/trips/index1.json.erb
<h1>Listing Trips</h1>

<%= link_to 'Add New Journey', new_trip_path %>

<br />

<table border="5", width="80%" >
  <tr>
    <th>Journey Name</th>
    <th>IMEI No</th>
    <th>Start Latitude</th>
    <th>Start Longitude</th>
    <th>Stop Latitude</th>
    <th>Stop Longitude</th>
    <th>Average Speed</th>
    <th></th>
  </tr>
 
  <% @trip.each do |trp| %>
    <tr>
      <td><%= trp.journey_name %></td>
      <td><%= trp.imei_no %></td>
      <td><%= trp.start_latitude %></td>
      <td><%= trp.start_longitude %></td>
      <td><%= trp.stop_latitude %></td>
      <td><%= trp.stop_longitude %></td>
      <td><%= trp.avg_spd %></td>
      <td><%= link_to 'Show', trip_path(trp) %></td>
      <td><%= link_to 'Edit', edit_trip_path(trp) %></td>
    </tr>
  <% end %>
</table>

app/views/trips/new.html.erb
<h1>New Trip</h1>

<%= form_for :trip, url: trips_path do |f| %>

	<% if @trip.errors.any? %>
	    <div id="error_explanation">
	      <h3>
	        <%= pluralize(@trip.errors.count, "error") %> Prohibited This Trip From Being Saved:
	      </h3>
	      <ul>
	        <% @trip.errors.full_messages.each do |msg| %>
	          <li><%= msg %></li>
	        <% end %>
	      </ul>
	    </div>
  	<% end %>
	 
	<p>
		<%= f.label "Journey Name:" %>
		<%= f.text_field :journey_name %>
	</p>
	
	<p>
		<%= f.label "IMEI NO:" %>
		<%= f.text_field :imei_no %>
	</p>
	
	<p>
		<%= f.label "Start Latitude:" %>
		<%= f.text_field :start_latitude %>
	</p>
	
	<p>
		<%= f.label "Start Longitude:" %>
		<%= f.text_field :start_longitude %>
	</p>
	
	<p>
		<%= f.label "Remarks:" %>
		<%= f.text_field :remarks %>
	</p>
	
	
	<br/>
	
	<p>
		<%= f.submit 'Start' %>
	</p>

<% end %>

<%= link_to 'Back', trips_path %>

app/views/trips/show.html.erb
<h1>Show Trip</h1>

<%= link_to 'New Journey', new_trip_path %> | <%= link_to 'Journey List', trips_path %> | <%= link_to 'Edit', edit_trip_path %>

<p>
  <strong>Journey Name:</strong>
  <%= @trip.journey_name %>
</p>
 
<p>
  <strong>IMEI No:</strong>
  <%= @trip.imei_no %>
</p>

<p>
  <strong>Start Latitude:</strong>
  <%= @trip.start_latitude %>
</p>

<p>
  <strong>Start Longitude:</strong>
  <%= @trip.start_longitude %>
</p>

<p>
  <strong>Stop Latitude:</strong>
  <%= @trip.stop_latitude %>
</p>

<p>
  <strong>Stop Longitude:</strong>
  <%= @trip.stop_longitude %>
</p>

<p>
  <strong>Average Speed:</strong>
  <%= @trip.avg_spd %>
</p>

<p>
  <strong>Remarks:</strong>
  <%= @trip.remarks %>
</p>

<h3>Overspeed :-</h3>
<% @trip.ovrspds.each do |spd| %>
  <p>
    <strong>Overspeed:</strong>
    <%= spd.over_speed %>
  </p>
 
  <p>
    <strong>Overspeed Latitude:</strong>
    <%= spd.ovrspd_latitude %>
  </p>

  <p>
    <strong>Overspeed Longitude:</strong>
    <%= spd.ovrspd_longitude %>
  </p>

<% end %>


<h3>Add Overspeed:</h3>
<%= form_for([@trip, @trip.ovrspds.build]) do |f| %>

  <p>
    <%= f.label :overspeed %><br>
    <%= f.text_field :over_speed %>
  </p>

  <p>
    <%= f.label :overspeed_latitude %><br>
    <%= f.text_field :ovrspd_latitude %>
  </p>
	
  <p>
    <%= f.label :overspeed_longitude %><br>
    <%= f.text_field :ovrspd_longitude %>
  </p>
	
  <p>
    <%= f.submit 'Overspeed' %>
  </p>

<% end %>

app/views/users/new.html.erb
<% @page_title = "UserAuth | Signup" %>
<div class="Sign_Form">
  <h1>Sign Up</h1>
  <%= form_for(:user, :url => {:controller => 'users', :action => 'create'}) do |f| %>
    
    <p> Email:</br> <%= f.text_field :email%> </p>
    <p> Password:</br> <%= f.password_field :password%></p>
    <!-- <p> Password Confirmation:</br> <%= f.password_field :password_confirmation%> </p> -->
    <%= f.submit :Signup %>
  <% end %>
  <% if @user.errors.any? %>
    <ul class="Signup_Errors">
	    <% for message_error in @user.errors.full_messages %>
	      <li>* <%= message_error %></li>
	    <% end %>
    </ul>
  <% end %>
</div>

app/views/welcome/index.html.erb
<div class="titledisplay">Welcome To My Journey Application.. <%= @user.email %></div> 

<div class="addjourney"><%= link_to 'Click to Show Journey List', controller: 'trips', id:@user.id %></div>

<div class="addjourney"><%= link_to 'Click to Show Journey List Json', controller: 'trips', action: 'index1', id:@user.id %></div>

<!-- <%= link_to('Logout', :controller=> "sessions", :action=> "new", :method => :delete) %> -->